baseurl = "https://miscellanea.us"
DefaultContentLanguage = "en"
title = "Tanvi Jakkampudi"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-122339572-1"

[Params]
  homeTitle = "Miscellanea" # Set a different text for the header on the home page
  subtitle = "Bits & Pieces of my life!"
  logo = "https://avatars2.githubusercontent.com/u/7349632?s=460&v=4"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
  gcse = "001646123108375388830:ivjibhuwqta" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Miscellea.us"
  website = "miscellanea.us"
  email = "hello@miscellanea.us"
  facebook = "tanvi.jay"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "tanvi2000"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
  linkedin = "Tanvi-Jakkampudi-21b705103"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
  instagram = "tanvijakkampudi"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
  vsco = "tanvijay"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    weight = 2

[[menu.main]]
    parent = "categories"
    name = "Notes"
    url = "tags/"
    weight = 1

[[menu.main]]
    parent = "categories"
    name = "Posts"
    url = "tags/"
    weight = 2

[[menu.main]]
    parent = "categories"
    name = "News"
    url = "tags/news"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
